#+TITLE: My Notetaking System
#+DATE: 2020-12-23
#+TAGS: misc

* My Notetaking System
  :PROPERTIES:
  :CUSTOM_ID: my-notetaking-system
  :END:

In my 10+ years as a graduate student, at three different institutions, I've tried so many notetaking systems. I started on paper, with [[https://en.wikipedia.org/wiki/Cornell_Notes][the Cornell Note methodology.]]. Then, once I got a laptop, I moved to web-based utilities, like [[https://evernote.com/][Evernote]]. After one of these, [[https://en.wikipedia.org/wiki/Springpad][Springpad]], bit the dust as a company, I realized I needed my own solution for notes that didn't rely on an external web service. I quickly fell in love with [[https://en.wikipedia.org/wiki/Tomboy_(software)][Tomboy Notes]], which is like a superpowered Sticky Note system. The best feature of Tomboy, along with its later clone, [[https://en.wikipedia.org/wiki/Gnote][Gnote]], was that if you were writing one note, and happened to type the name of another note, it would automatically link to that other note. This meant you could have small, stickynote-sized notes and have them all relate to each other.

This was amazingly empowering, because the notes I was taking were really all interconnected. Especially as a student of early 20th Century British literature: so many of the canonical figures of the field knew each other, published each other, and influenced each other. But Tomboy had its limitations, and really started to choke with a larger amount of notes, edits, and syncs with its server. Here again, I was in a similar situation as before: I had developed a huge note database in software that wasn't totally reliable.

So I switched to plain-text notes. There's not much that can go wrong when you're just editing a plain text file with a text editor. At that same time, I was also learning [[https://en.wikipedia.org/wiki/Vim_(text_editor)][Vim]], the modal text editor, and suddenly writing in any other program felt clunky and inefficient in comparison. So I moved all my notes into plain text. Then I discovered [[https://github.com/xolox/vim-notes][vim-notes]], the wonderful Tomboy-like system. But vim-notes used its own brand of markup, which wasn't /quite/ Markdown, and wasn't quite any other format, either, which made export and compatibility with external programs a little unweildy. Around that time, I heard about [[https://en.wikipedia.org/wiki/Org-mode][Org-mode]].

I say this without exaggeration: /org-mode is the best organizational software around/. It's a personal information manager, notetaking system, calendar, time tracker, and much more. There's really nothing like it. If you've never heard of it, I'd recommend watching [[https://www.youtube.com/results?search_query=org+mode][one of the many introductory videos out there]]. Org-mode was the reason I switched from Vim to Emacs (although I got to keep my familiar keybindings, via [[https://www.spacemacs.org/][Spacemacs]] and eventually [[https://github.com/hlissner/doom-emacs][Doom Emacs]]).

Soon, I discovered that there are a lot of extensions to Org, and some of them help with academic notetaking. One of them, org-roam, emulates [[https://en.wikipedia.org/wiki/Zettelkasten][Zettelkasten-style]] notetaking programs like [[https://roamresearch.com/][Roam Research]],
